[package]
name = "reader"
version = "0.1.0"
authors = ["Dmitry Vrublevsky <dmitry@vrublevsky.me>"]
edition = "2018"

[dependencies]
env_logger = "0.7.1"
log = "0.4.8"
rust-embed = "5.1.0"
rocket = "0.4.2"
r2d2 = "0.8.6"
r2d2_sqlite = "0.12.0"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
time = "0.1.42"

[dependencies.rocket_contrib]
version = "0.4.2"
default-features = false
features = ["json", "helmet"]

[dependencies.rusqlite]
version = "0.20.0"
features = ["bundled"]
