[config]
skip_core_tasks = true

[tasks.backend-check]
command = "cargo"
args = ["check", "--all-targets"]

[tasks.backend-format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt"]

[tasks.backend-format-check]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--check"]

[tasks.backend-test]
command = "cargo"
args = ["test"]

[tasks.backend-build]
command = "cargo"
args = ["build", "--release"]

[tasks.frontend-lint]
cwd = "./app"
install_script = ["yarn lint"]

[tasks.frontend-fix]
cwd = "./app"
install_script = ["yarn fix"]

[tasks.frontend-test]
cwd = "./app"
install_script = ["yarn test --watchAll=false"]

[tasks.frontend-build]
cwd = "./app"
install_script = ["yarn build"]

[tasks.verify]
dependencies = [
    "frontend-lint",
    #"frontend-test",
    "backend-check",
    "backend-format-check",
    "backend-test",
]

[tasks.build]
dependencies = [
    "frontend-build",
    "backend-build",
]

[tasks.fix]
dependencies = [
    "frontend-fix",
    #"frontend-test",
    "backend-check",
    "backend-test",
    "backend-format",
]

[tasks.default]
alias = "fix"
