[config]
skip_core_tasks = true

[tasks.backend-clean]
command = "cargo"
args = ["clean"]

[tasks.backend-check]
command = "cargo"
args = ["check", "--all-targets"]

[tasks.backend-format]
command = "cargo"
args = ["fmt"]

[tasks.backend-format-check]
command = "cargo"
args = ["fmt", "--", "--check"]

[tasks.backend-test]
command = "cargo"
args = ["test"]

[tasks.backend-build]
command = "cargo"
args = ["build", "--release"]

[tasks.frontend-clean]
cwd = "./app"
install_script = ["rm -rf build/"]

[tasks.frontend-install]
cwd = "./app"
install_script = ["yarn install"]

[tasks.frontend-format]
cwd = "./app"
install_script = ["yarn fmt"]

[tasks.frontend-format-check]
cwd = "./app"
install_script = ["yarn fmt-check"]

[tasks.frontend-lint]
cwd = "./app"
install_script = ["yarn lint"]

[tasks.frontend-lint-fix]
cwd = "./app"
install_script = ["yarn lint-fix"]

[tasks.frontend-test]
cwd = "./app"
install_script = ["yarn test --watchAll=false"]

[tasks.frontend-build]
cwd = "./app"
install_script = ["yarn build"]

[tasks.clean]
dependencies = [
    "frontend-clean",
    "backend-clean",
]

[tasks.build]
dependencies = [
    "frontend-install",
    "frontend-build",
    "backend-build",
]

[tasks.verify]
dependencies = [
    "frontend-install",
    "frontend-format-check",
    "frontend-lint",
    "backend-check",
    "backend-format-check",
    "backend-test",
]

[tasks.fix]
dependencies = [
    "frontend-install",
    "frontend-format",
    "frontend-lint-fix",
    "backend-check",
    "backend-format",
    "backend-test",
]

[tasks.deploy]
install_script = [
    "ssh reader 'systemctl stop reader || true'",
    "ssh reader 'mkdir -p ~/reader'",
    "scp target/release/reader reader:~/reader/reader",
    "scp fixture_production.sql reader:~/reader/fixture.sql",
    "scp docs/reader.service reader:/etc/systemd/system/reader.service",
    "ssh reader 'systemctl daemon-reload'",
    "ssh reader 'systemctl restart reader'",
    "sleep 1",
    "ssh reader 'systemctl status reader'",
]

[tasks.default]
alias = "fix"
